.TH UNLINK 1 "March 2015" "User Manuals"


.SH NAME
unlink \- call the unlink function to remove a file


.SH SYNOPSIS
.TP
unlink [OPTION]
.TP
unlink [FILE]


.SH DESCRIPTION
.B unlink
calls the unlink function to remove the specified file.


.SH OPTIONS
.TP
\fB-h or --help\fP
Print quick usage details to the screen.
.TP
\fB-V or --version\fP
Print version information to the screen.

.SH FILES
none


.SH BUGS
POSIX compliant - IEEE Std 1003.1, 2013 Edition

.SH AUTHOR
Darren Kirby <bulliver@gmail.com>

.SH "SEE ALSO"
link(1), rm(1), rmdir(1), unlink(2)
