.TH WHOAMI 1 "March 2015" "User Manuals"


.SH NAME
whoami \- print effective userid


.SH SYNOPSIS
.B whoami
[
.I OPTIONS
]


.SH DESCRIPTION

Print the user name associated with the current effective user ID.  Same as id -un.


.SH OPTIONS
.TP
\fB-h or --help\fP
Print quick usage details to the screen.
.TP
\fB-V or --version\fP
Print version information to the screen.


.SH AUTHOR
Darren Kirby <bulliver@gmail.com>

.SH "SEE ALSO"
.BR who (1),
.BR id(1)
