.TH YES 1 "March 2015" "User Manuals"


.SH NAME
yes \- output a string repeatedly until killed


.SH SYNOPSIS
.B yes [
.I STRING
.B ]
.TP
.B yes [
.I OPTION
]


.SH DESCRIPTION
Repeatedly output a line with all specified STRING(s), or 'y'.


.SH OPTIONS
.TP
\fB-h or --help\fP
Print quick usage details to the screen.
.TP
\fB-V or --version\fP
Print version information to the screen.


.SH AUTHOR
Darren Kirby <bulliver@gmail.com>
